-- 1) Ensure absences.id autogenerates and add triggers for validation and audit
-- Make id a generated identity if it isn't already
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'absences'
      AND column_name = 'id'
      AND is_identity = 'YES'
  ) THEN
    ALTER TABLE public.absences
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- 2) Create BEFORE INSERT trigger to set defaults and validate
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger
    WHERE tgname = 'trg_absences_set_defaults_validate'
  ) THEN
    CREATE TRIGGER trg_absences_set_defaults_validate
    BEFORE INSERT ON public.absences
    FOR EACH ROW
    EXECUTE FUNCTION public.absences_set_defaults_validate();
  END IF;
END $$;

-- 3) Attach enhanced audit trigger on absences for insert/update/delete
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger
    WHERE tgname = 'trg_absences_audit'
  ) THEN
    CREATE TRIGGER trg_absences_audit
    AFTER INSERT OR UPDATE OR DELETE ON public.absences
    FOR EACH ROW
    EXECUTE FUNCTION public.enhanced_audit_log();
  END IF;
END $$;