// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atogozlqfwxztjyycjoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0b2dvemxxZnd4enRqeXljam95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDQ3MjksImV4cCI6MjA2NTY4MDcyOX0.m9c9XOJoU0RQeCentl1Ibow5yBqS6NfJVpxBaF75-ik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Verificar se localStorage está disponível (iOS modo privado pode bloquear)
const isLocalStorageAvailable = () => {
  try {
    const test = '__storage_test__';
    localStorage.setItem(test, test);
    localStorage.removeItem(test);
    return true;
  } catch (e) {
    console.warn('⚠️ localStorage não disponível (modo privado?), usando storage temporário');
    return false;
  }
};

let supabase: ReturnType<typeof createClient<Database>> | any;
try {
  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: isLocalStorageAvailable() ? localStorage : undefined,
      persistSession: isLocalStorageAvailable(),
      autoRefreshToken: true,
    }
  });
} catch (e) {
  console.warn('⚠️ Supabase não configurado corretamente. Preview continuará com funcionalidades limitadas.');
  const notConfigured = () => { throw new Error('Supabase não configurado') };
  supabase = {
    auth: {
      signInWithPassword: notConfigured,
      signUp: notConfigured,
      signOut: notConfigured,
      getSession: notConfigured,
    },
    from: () => ({ select: notConfigured, insert: notConfigured, update: notConfigured, delete: notConfigured }),
    functions: { invoke: notConfigured },
    storage: { from: () => ({ upload: notConfigured, getPublicUrl: notConfigured, remove: notConfigured }) },
  };
}

export { supabase };
